kernel:
  name: 'exponential'
  var: 1.
  length_scale: 0.1
gp_covar_eps: 1.0e-10

# Model parameters
n_critic: 1
#n_critic: 5
l_grad: 0.10
#l_grad: 10.0

# Training / Optimization Parameters
epochs: 50 # TOCHANGE
#batch_size: 128
optim_params:
  lr: 0.001
  weight_decay: 1e-4  # FNO1d uses 1e-4

# Data parameters
n_x: 64 # TOCHANGE
x_min: 0.
x_max: 1.

# Etc.
device: 'cuda'  # ['cpu', 'cuda']
dtype: 'double'  # ['float', 'double']